language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ant
before_script: ./scripts/generate-mo --quiet
script: ant phpunit-nocoverage lint
