# The Travis setup:
# - run testsuite for every PHP version
# - run lint for every PHP version
# - run Selenium for single PHP version

language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - hhvm
env:
  matrix:
    - PHPUNIT_ARGS="--exclude-group selenium"
    - LINT="yes"
  global:
    # BrowserStack key:
    - secure: "hwfXo/2UMLuCZrMU/mbsdfYXQ6CvFI8WMH0IHqsdig5Q1mYrIr1TDM47gwOPVzlZDwxVD51vuwxxUepet/XFt/41J4mL3R10vGf6HGuh1OQIOoAvANLiEPSsxaB7PtF9S9RBe90We4TOWaHHoUfdCD/Uv+xwyWDxD6FQRQKHD4w="
    - TESTSUITE_BROWSERSTACK_USER=michaliha
    - TESTSUITE_USER=root
    - TESTSUITE_PASSWORD=root
before_script:
  - if [[ -z "$LINT" ]] ; then
    if [[ $TRAVIS_PHP_VERSION != "hhvm" ]] ; then

    git clone --depth=1 git://github.com/zenovich/runkit.git ;
    cd runkit ;
    phpize ;
    ./configure ;
    make ;
    make install ;
    cd .. ;

    phpenv config-add test/travis.php.ini ;

    pear channel-discover pear.phpunit.de ;
    pear install phpunit/PHPUnit_Selenium ;

    composer install --dev --no-interaction ;

    fi ;

    if [[ ! -z "$SELENIUM" ]] ; then

    php --server 127.0.0.1:8000 &
    wget http://www.browserstack.com/BrowserStackTunnel.jar ;
    java -jar BrowserStackTunnel.jar -localIdentifier "travis-$TRAVIS_JOB_NUMBER" -onlyAutomate "$TESTSUITE_BROWSERSTACK_KEY" 127.0.0.1,8000,0 &

    mysql -uroot < examples/create_tables.sql ;
    mysql -uroot -e 'SET PASSWORD = PASSWORD("root")' ;

    fi ;
    fi
script:
  - ant locales
  - if [[ -z "$LINT" ]] ; then
    export TESTSUITE_URL="http://127.0.0.1:8000" ;
    if [[ $TRAVIS_PHP_VERSION == "hhvm" ]] ; then
    ant phpunit-hhvm ;
    else
    ant phpunit ;
    fi ;
    else
    ant lint ;
    fi
after_script:
  - php vendor/bin/coveralls -v
matrix:
  allow_failures:
    - php: hhvm
      env: PHPUNIT_ARGS="--exclude-group selenium"
    - php: 5.5
      env: PHPUNIT_ARGS="--group selenium" SELENIUM="yes"
  fast_finish: true
  include:
    - php: 5.5
      env: PHPUNIT_ARGS="--group selenium" SELENIUM="yes"
