language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - hhvm
env:
  matrix:
    - PHPUNIT_ARGS="--exclude-group selenium"
    - LINT="yes"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ant
before_script:
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" -a -z "$LINT" ]] ; then
    git clone git://github.com/zenovich/runkit.git && cd runkit && phpize && ./configure && make && make install && cd .. ;
    phpenv config-add test/travis.php.ini ;
    pear channel-discover pear.phpunit.de ;
    pear install phpunit/PHPUnit_Selenium ;
    fi
  - if [[ -z "$LINT" ]] ; then
    composer install --dev --no-interaction ;
    fi
script:
  - if [[ -z "$LINT" ]] ; then
    if [[ $TRAVIS_PHP_VERSION == "hhvm" ]] ; then
    ant phpunit-hhvm ;
    else
    ant phpunit ;
    fi ;
    else
    ./scripts/generate-mo --quiet ;
    ant lint ;
    fi
after_script:
  - php vendor/bin/coveralls -v
matrix:
  allow_failures:
    - php: hhvm
      env: PHPUNIT_ARGS="--exclude-group selenium"
  fast_finish: true
  include:
    - php: 5.5
      env: PHPUNIT_ARGS="--group selenium"
