language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - hhvm
env:
  matrix:
    PHPUNIT_ARGS="--exclude-group selenium"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ant
before_script:
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]] ; then
    git clone git://github.com/zenovich/runkit.git && cd runkit && phpize && ./configure && make && make install && cd .. ;
    phpenv config-add test/travis.php.ini ;
    pear channel-discover pear.phpunit.de ;
    pear install phpunit/PHPUnit_Selenium ;
    fi
  - composer install --dev --no-interaction
script:
  - ./scripts/generate-mo --quiet
  - if [[ $TRAVIS_PHP_VERSION == "hhvm" ]] ; then ant phpunit-hhvm ; else ant phpunit ; fi
  - ant lint
after_script:
  - php vendor/bin/coveralls -v
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  include:
    - php: 5.5
      env: PHPUNIT_ARGS="--group selenium"
